// 12 個 micro-phase 對應的「從這裡開始」hint
// 依據 dt-flow-spec-v4.md，每個 micro 都有 Aria 第一人稱示範 + 4 張師徒制卡片
// 透過 resolveStageHint(stage, microPhase) 由 stageStartHints.ts 統一取用

import {
  Sparkles,
  ClipboardPaste,
  LayoutTemplate,
  Copy,
  Layers,
  Lightbulb,
  Pencil,
  Brain,
  Vote,
  Frame,
  TestTube,
  ListChecks,
  Repeat,
  Target,
  Users,
  Map as MapIcon,
  ScrollText,
  Eye,
  Quote,
  Shuffle,
  Ruler,
  ClipboardCheck,
  Compass,
} from 'lucide-react'
import type { MicroPhaseId } from '../../types/models'
import type { StageStartHint } from './stageStartHints'

export const MICRO_PHASE_HINTS: Record<MicroPhaseId, StageStartHint> = {
  // ───────────────────── Discover ─────────────────────
  '1.1': {
    stage: 'discover',
    narrative: {
      ariaSays:
        '1.1 暖場：別急著訪別人，先讓團隊各自把「我對這議題的經驗」說出來，再獨立列出利害關係人。',
      example: '我自己用過共享單車，最煩的是「掃了 3 台都騎不動」——那次我沒抱怨給誰聽。',
      delayJudgment: '經驗分享不評價、不討論解法；利害關係人先各自寫，再揭示避免群體思維。',
    },
    actions: [
      {
        id: 'ai_warmup',
        title: '請 AI 帶暖場問題',
        body: 'Aria 拋 1 題經驗類問題',
        icon: Sparkles,
        recommended: true,
        role: 'modeling',
        scaffold: '「你在 [TOPIC] 的經驗是什麼？」',
        articulation: '不評價、不解法，先各自說 1–2 分鐘。',
        pitfall: '不要立刻跳到「所以我們應該做…」——這時還沒有資格談解法。',
      },
      {
        id: 'paste_experience',
        title: '寫經驗短句',
        body: '把自己的經驗外部化',
        icon: ScrollText,
        role: 'scaffolding',
        scaffold: '30 字內：「我在 X 場景做 Y，感受 Z」',
        articulation: '是「親身經驗」還是「聽說的故事」？',
        pitfall: '別只寫結論（「很難用」）——要留下情境與情緒。',
      },
      {
        id: 'list_stakeholders',
        title: '獨立列利害關係人',
        body: '各自寫名單再揭示',
        icon: Users,
        role: 'scaffolding',
        scaffold: '每人寫 ≥5 個受影響的角色',
        articulation: '你選的這群人，誰是直接、誰是間接？',
        pitfall: '先別看別人的清單——避免抄襲與群體思維。',
      },
      {
        id: 'scope_rationale',
        title: '揭示歸類 + 範疇理由',
        body: '收斂時附 scope rationale',
        icon: Compass,
        role: 'coaching',
        scaffold: '「選這群、不選那群」的理由',
        articulation: '為什麼這群是焦點？不是這群的代價是什麼？',
        pitfall: '沒有 rationale 的話，Define 階段失去 traceback，會回不來。',
      },
    ],
  },

  '1.2': {
    stage: 'discover',
    narrative: {
      ariaSays:
        '1.2 視角擴展：依利害關係人分工去蒐集——訪談、觀察、二手資料三管齊下，不要只靠單一管道。',
      example: '銷售端我用訪談、長照家屬我用觀察、政策面我去翻三篇報告——交叉比對才接近真實。',
      delayJudgment: '訪談中沉默是資料，不要急著補話；probe 等對方話講完再丟。',
    },
    actions: [
      {
        id: 'ai_interview_outline',
        title: '請 AI 草擬訪談大綱',
        body: '5W1H 結構化問題',
        icon: Sparkles,
        recommended: true,
        role: 'modeling',
        scaffold: '5W1H：Who/What/When/Where/Why/How',
        articulation: '這份大綱在問「事實」還是「觀點」？',
        pitfall: 'AI 容易出封閉式問題——逼它至少一半改成開放式。',
      },
      {
        id: 'interview_tips',
        title: '訪談技巧提示卡',
        body: '專家行為清單',
        icon: ClipboardCheck,
        role: 'scaffolding',
        scaffold: '沉默＝資料／話講完再 probe／could you say more',
        articulation: '你最近一次訪談，打斷了幾次？',
        pitfall: '中途打斷會把對話推向防禦——讓對方先講完。',
      },
      {
        id: 'observe_journey',
        title: '觀察 Journey Map',
        body: '看使用者目前怎麼做',
        icon: MapIcon,
        role: 'scaffolding',
        scaffold: '每一步：做什麼／想什麼／感受／痛點',
        articulation: '觀察到的「行為」跟使用者口述的「說法」一致嗎？',
        pitfall: '別只記步驟——情緒與卡點才是金礦。',
      },
      {
        id: 'copy_previous',
        title: '從先前訪談複製',
        body: '借用過去的訪談大綱',
        icon: Copy,
        role: 'coaching',
        scaffold: '上次的訪談 Insight，這次重新檢視',
        articulation: '上次的脈絡跟這次一樣嗎？',
        pitfall: '結論會過期，洞察才可遷移——先檢視「為什麼上次成立」。',
      },
    ],
  },

  '1.3': {
    stage: 'discover',
    narrative: {
      ariaSays:
        '1.3 同理心收斂：先把訪談原音保留下來，再用 Empathy Map / Persona / Journey 三種模板整理；解讀放最後。',
      example: '〔受訪者 A・3:42〕「我每天要按 18 次才能扣到款」｜情緒：無奈｜（解讀：操作疲乏）',
      delayJudgment: '禁止這時就寫「使用者真正的需求是 X」——歸因要等模板填完。',
    },
    actions: [
      {
        id: 'paste_transcript',
        title: '貼上訪談逐字稿',
        body: '從文字檔產生洞察便利貼',
        icon: ClipboardPaste,
        recommended: true,
        role: 'modeling',
        scaffold: '〔人・時間〕「原句」＋情緒 tag',
        articulation: '哪句是事實？哪句是你的解讀？',
        pitfall: '不要把推測寫成引用——原句要打引號，解讀另外註記。',
      },
      {
        id: 'empathy_map',
        title: '填 Empathy Map',
        body: 'Says / Thinks / Does / Feels',
        icon: Eye,
        role: 'scaffolding',
        scaffold: '四象限分開「說的」與「我們推測的」',
        articulation: 'Thinks 那格的依據是哪句原話？',
        pitfall: '別把 Thinks 寫成「使用者其實想要 X」——這是解讀，不是觀察。',
      },
      {
        id: 'create_persona',
        title: '建立 Persona 卡',
        body: '把利害關係人具象化',
        icon: Users,
        role: 'scaffolding',
        scaffold: '姓名／背景／目標／痛點／典型一天',
        articulation: '這位 Persona 解決了哪一群利害關係人？',
        pitfall: '別只憑想像——每個欄位都要有訪談證據。',
      },
      {
        id: 'says_vs_thinks',
        title: '區分 Says vs Thinks',
        body: '檢查需求 vs 解方',
        icon: Quote,
        role: 'coaching',
        scaffold: '「我想要更大的按鈕」＝解方；「希望操作被注意到」＝需求',
        articulation: '使用者說的，是需求還是解方？',
        pitfall: '把解方當需求記下來，會把後面的設計綁死。',
      },
    ],
  },

  // ───────────────────── Define ─────────────────────
  '2.1': {
    stage: 'define',
    narrative: {
      ariaSays:
        '2.1 旅程追蹤：把訪談痛點放回使用者旅程的對應節點——讓痛點長在「具體場景」上，而不是抽象標籤。',
      example: '〔結帳頁・運費揭露〕痛點：使用者要點到第 3 頁才看到運費 → 情緒從期待轉為猶豫。',
      delayJudgment: '不要急著歸納主題，先把痛點放回時間序列上。',
    },
    actions: [
      {
        id: 'cluster_by_stage',
        title: '按旅程節點分群',
        body: '同一節點的痛點放一起',
        icon: MapIcon,
        recommended: true,
        role: 'scaffolding',
        scaffold: '旅程節點 × 痛點便利貼',
        articulation: '這個節點有幾個獨立痛點？',
        pitfall: '別硬把不同節點的痛點塞進同一群。',
      },
      {
        id: 'emotion_curve',
        title: '畫情緒曲線',
        body: '看高點與低點在哪',
        icon: Sparkles,
        role: 'modeling',
        scaffold: '時間軸 × 情緒（-2 到 +2）',
        articulation: '最深的低點落在哪一步？',
        pitfall: '別把全部都畫成負——找出對比才有設計切入點。',
      },
      {
        id: 'cluster_insights',
        title: '群聚便利貼',
        body: 'Affinity Mapping',
        icon: Layers,
        role: 'scaffolding',
        scaffold: '分群→命名→留下「為何屬於這群」的便條',
        articulation: '這群的共同主題是「需求」還是「現象」？',
        pitfall: '別用「主題標籤」蓋掉個別差異——先讓張力浮出來。',
      },
      {
        id: 'find_tension',
        title: '標記矛盾與張力',
        body: '相反方向的訊號最珍貴',
        icon: Shuffle,
        role: 'coaching',
        scaffold: '「A 群想要 X，但 B 群恰好需要相反」',
        articulation: '張力背後共同需要的是什麼？',
        pitfall: '別只挑「大家都同意」的洞察——共識少的地方常有設計空間。',
      },
    ],
  },

  '2.2': {
    stage: 'define',
    narrative: {
      ariaSays:
        '2.2 洞察萃取：用 POV 句型寫出至少 3 個候選，每個都要回去引用 ≥2 筆 Discover 觀察作為佐證。',
      example:
        'POV：〔電商新手〕需要〔在商品列表頁就感知運費〕，因為〔運費高低決定他是否完成購買〕。',
      delayJudgment: '紅旗詞：build／design／做一個／應該要——出現就先暫停。',
    },
    actions: [
      {
        id: 'write_pov',
        title: '草擬 POV',
        body: '至少寫 3 個候選',
        icon: Target,
        recommended: true,
        role: 'modeling',
        scaffold: '〔User〕需要〔Need〕，因為〔Insight〕',
        articulation: '為什麼這個需求對「這位」用戶為真？',
        pitfall: 'INSIGHT 不能只是把 Need 換句話說——要說出背後的洞察。',
      },
      {
        id: 'cite_evidence',
        title: '附訪談佐證',
        body: '每個 POV 引 ≥2 筆觀察',
        icon: Quote,
        role: 'scaffolding',
        scaffold: 'POV ← 引用〔人・時間〕「原句」',
        articulation: '佐證是事實還是你的詮釋？',
        pitfall: '沒有佐證的 POV 是想像——回 Discover 補資料。',
      },
      {
        id: 'socratic_why',
        title: '持續追問為什麼',
        body: 'Socratic 五層',
        icon: Brain,
        role: 'scaffolding',
        scaffold: '針對痛點問 5 次「為什麼」',
        articulation: '第 3 層的答案還是表面嗎？',
        pitfall: '別在第 1 層停下——表面問題不是真正的問題。',
      },
      {
        id: 'check_solutionish',
        title: '掃描解法語言',
        body: '紅旗詞偵測',
        icon: ClipboardCheck,
        role: 'coaching',
        scaffold: 'build／design／做一個／應該要 = 紅旗',
        articulation: '你的 POV 有沒有偷渡 how？',
        pitfall: '出現紅旗詞 → 改寫成「使用者需要什麼狀態」。',
      },
    ],
  },

  '2.3': {
    stage: 'define',
    narrative: {
      ariaSays:
        '2.3 HMW：先建收斂準則（不能直覺投票）→ 選 1–3 個 POV → 改寫為 How Might We 開放式挑戰。',
      example: 'HMW：我們如何讓電商新手在「商品列表頁」就感知到運費資訊？',
      delayJudgment: 'HMW 不能偷渡解法——「做一個 App」不是 HMW。',
    },
    actions: [
      {
        id: 'define_criteria',
        title: '建立收斂準則',
        body: '先定義模範生',
        icon: Ruler,
        recommended: true,
        role: 'scaffolding',
        scaffold: '影響力／可學到的事／可行性／差異化',
        articulation: '我們的判準有沒有對齊團隊共識？',
        pitfall: '別在投票後才補判準——順序顛倒等於合理化直覺。',
      },
      {
        id: 'dot_vote',
        title: '依準則投票',
        body: '選出 1–3 個高優先級',
        icon: Vote,
        role: 'scaffolding',
        scaffold: '每人 3 點，依準則加權',
        articulation: '這次投票對應的是哪一條準則？',
        pitfall: '超過 3 個進入 Phase 3 會認知過載——強制收斂。',
      },
      {
        id: 'rewrite_hmw',
        title: '改寫為 HMW',
        body: 'POV → How Might We',
        icon: Lightbulb,
        role: 'modeling',
        scaffold: 'How Might We [動詞] [群體] [所欲狀態]？',
        articulation: '你的 HMW 是否仍偷渡解法？',
        pitfall: '「做一個 App」不是 HMW——拉回需求層級。',
      },
      {
        id: 'check_existing',
        title: '盤點既有解法',
        body: '別重複造輪子',
        icon: Compass,
        role: 'coaching',
        scaffold: '已被解決／部分解決／未被解決',
        articulation: '我們的 HMW 攻的是哪一塊缺口？',
        pitfall: '別把「已被好好解決」當機會點——精力放在真正的缺口。',
      },
    ],
  },

  // ───────────────────── Develop ─────────────────────
  '3.1': {
    stage: 'develop',
    narrative: {
      ariaSays:
        '3.1 規則建立與大量發散：先立規則（不批判、外部化、量先於質）→ 每人獨立寫點子，禁止口頭講過就消失。',
      example: '針對「列表頁感知運費」的 HMW，我先 8 分鐘各自寫 ≥8 個點子，再揭示。',
      delayJudgment: '此階段完全不討論可行性——可行性是 Phase 4 的事。',
    },
    actions: [
      {
        id: 'crazy_eights',
        title: 'Crazy 8s 草圖',
        body: '8 分鐘畫 8 個構想',
        icon: Pencil,
        recommended: true,
        role: 'modeling',
        scaffold: '8 格／8 分鐘／一格一構想',
        articulation: '你卡住的是「沒點子」還是「在自我審查」？',
        pitfall: '第 5 格之後才是真發散——別在第 3 格就放棄。',
      },
      {
        id: 'set_rules',
        title: '寫下發散規則',
        body: '不批判／外部化／量先',
        icon: ScrollText,
        role: 'scaffolding',
        scaffold: '規則貼在白板顯眼處',
        articulation: '剛剛有沒有人說「這做不到」？',
        pitfall: '沒寫規則 → 第一個「現實派」就會殺掉發散氛圍。',
      },
      {
        id: 'silent_brainstorm',
        title: '靜默發散',
        body: '先寫不講',
        icon: Brain,
        role: 'scaffolding',
        scaffold: '5–8 分鐘各自寫便利貼',
        articulation: '你只寫了「想到的」還是包含「不敢說的」？',
        pitfall: '口頭講過沒寫，後面就消失——強制外部化。',
      },
      {
        id: 'ai_propose',
        title: '請 Aria 提案',
        body: '讓 AI 補刺激',
        icon: Sparkles,
        role: 'coaching',
        scaffold: '把 HMW 丟給 Aria，要求 5 個不同方向',
        articulation: 'AI 的點子是補你的盲點還是同質擴張？',
        pitfall: 'AI 容易順著現有方向擴寫——逼它換機制。',
      },
    ],
  },

  '3.2': {
    stage: 'develop',
    narrative: {
      ariaSays:
        '3.2 分群合併：揭示全部點子 → 分群 → 從別人的便利貼延伸新想法——群體碰撞才產出 1+1>2。',
      example: '把「介面提示」與「實體場域改造」兩群並排 → 激發第三群「結帳前主動告知」。',
      delayJudgment: '分群是為了激發，不是淘汰——舊點子不准消失。',
    },
    actions: [
      {
        id: 'reveal_all',
        title: '揭示全部點子',
        body: '一次看完不評論',
        icon: Eye,
        recommended: true,
        role: 'modeling',
        scaffold: '一人 30 秒念自己的點子',
        articulation: '聽到別人念時，你想到的新點子寫下了嗎？',
        pitfall: '別在揭示階段討論優劣——只聽、只記、只發散。',
      },
      {
        id: 'cluster_ideas',
        title: '把點子分群',
        body: '同類放一起',
        icon: Layers,
        role: 'scaffolding',
        scaffold: 'Affinity：機制／場域／使用情境',
        articulation: '群的命名是「解法名稱」還是「共同機制」？',
        pitfall: '別用解法名稱當群名——機制才能激發跨群連結。',
      },
      {
        id: 'remix_ideas',
        title: '組合與延伸',
        body: '從別人的點子發芽',
        icon: Repeat,
        role: 'scaffolding',
        scaffold: '「A + B = ?」「A 套到 B 的場景會怎樣？」',
        articulation: '新延伸的點子有沒有貼回白板？',
        pitfall: '只在腦中組合不貼出來，等於沒發生。',
      },
      {
        id: 'find_extreme',
        title: '挖極端組合',
        body: '最不可能的兩個合起來',
        icon: Shuffle,
        role: 'coaching',
        scaffold: '隨機選兩個遠端點子強制配對',
        articulation: '這個極端組合裡有沒有 1% 可用的種子？',
        pitfall: '別馬上喊「這不可能」——先看核心機制。',
      },
    ],
  },

  '3.3': {
    stage: 'develop',
    narrative: {
      ariaSays:
        '3.3 評估收斂：先確認多樣性夠不夠（不是數量），再用 category-shift 補弱項，最後才選定方向。',
      example: '所有點子都在「加新功能」→ 我請你們改用「減步驟」再出 3 個。',
      delayJudgment: '選定前要先確認類別多樣——同機制的點子再多也是 fixation。',
    },
    actions: [
      {
        id: 'diversity_check',
        title: '多樣性檢查',
        body: '不是數量，是類別',
        icon: Eye,
        recommended: true,
        role: 'modeling',
        scaffold: '機制矩陣：加 vs 減／介面 vs 場域／單人 vs 多人',
        articulation: '矩陣裡有沒有完全空白的格子？',
        pitfall: '別把「點子很多」當多樣——很多時候只是同機制換皮。',
      },
      {
        id: 'category_shift',
        title: 'Category-shift 補弱',
        body: '指定機制再出 3 個',
        icon: Repeat,
        role: 'scaffolding',
        scaffold: '「現在所有點子都用 X，請改用 Y 再出 3 個」',
        articulation: '目前所有點子的共同機制是什麼？',
        pitfall: '「再多想一些」沒幫助——要指定方向。',
      },
      {
        id: 'preliminary_vote',
        title: '預備投票',
        body: '選看起來最有戲的',
        icon: Vote,
        role: 'scaffolding',
        scaffold: '每人 3 點，標出潛力高的點子',
        articulation: '你投的是因為「酷」還是「回應 HMW」？',
        pitfall: '別在 Develop 就做嚴格篩選——精細評估留到 4-1。',
      },
      {
        id: 'select_branch',
        title: '選定 1–2 條主軸',
        body: '進 Phase 4 的方向',
        icon: Target,
        role: 'coaching',
        scaffold: '主軸 = 一句話描述機制',
        articulation: '主軸是「機制」還是「成品」？',
        pitfall: '主軸太具體（「做 App」）會壓死 4-1 的雛形多樣性。',
      },
    ],
  },

  // ───────────────────── Deliver ─────────────────────
  '4.1': {
    stage: 'deliver',
    narrative: {
      ariaSays:
        '4.1 原型規劃：先口頭闡明假設 → 拆 Task Ticket → 強制 low-fidelity 第一版——禁寫 production code。',
      example:
        '假設：用戶願意在列表頁點開「運費詳情」icon。成功＝70% 受測者點。失敗＝沒人點。',
      delayJudgment: '保真度過高會偷渡解法——剛好夠回答假設就好。',
    },
    actions: [
      {
        id: 'write_hypothesis',
        title: '寫假設卡',
        body: '把要驗證的事說清楚',
        icon: Target,
        recommended: true,
        role: 'articulation',
        scaffold: '測試：X／成功＝Y／失敗＝Z／保真度＝…',
        articulation: '你在測「使用者願意」還是「技術做得到」？',
        pitfall: '沒有失敗條件的假設不能驗證——一定要寫出反證會長什麼樣。',
      },
      {
        id: 'write_tasks',
        title: '拆 Task Ticket',
        body: '對應假設的執行卡',
        icon: ListChecks,
        role: 'scaffolding',
        scaffold: 'Owner／DoD／時限／保真度上限',
        articulation: '完成定義（DoD）夠不夠客觀？',
        pitfall: '「做完原型」不是 DoD——要寫具體驗收條件。',
      },
      {
        id: 'lowfi_prototype',
        title: '低保真原型',
        body: '紙原型／Wireframe／Wizard-of-Oz',
        icon: Frame,
        role: 'modeling',
        scaffold: '剛好夠回答假設的保真度',
        articulation: '為什麼這個保真度就夠？',
        pitfall: '保真度過高 → 偷渡解法決策、增加迭代成本。',
      },
      {
        id: 'feasibility_screen',
        title: '可行性篩選',
        body: '時間／成本／技術條件',
        icon: Ruler,
        role: 'coaching',
        scaffold: '能不能在預算內被驗證？',
        articulation: '哪個方案最便宜就能拿到答案？',
        pitfall: '別把「酷」當可行——拿不出測試成本上限就先暫停。',
      },
    ],
  },

  '4.2': {
    stage: 'deliver',
    narrative: {
      ariaSays:
        '4.2 測試設計：給假設搭配可觀察的成功/失敗條件，與最低需要的保真度上限——這是準備跑測試的契約。',
      example: '測試方式：5 人各跑 3 分鐘 → 觀察是否主動點 icon → 記錄 quote 與情緒。',
      delayJudgment: '別設「願意使用嗎？」這種主觀題——要可觀察的行為。',
    },
    actions: [
      {
        id: 'design_protocol',
        title: '寫測試腳本',
        body: '受測者要做什麼',
        icon: ScrollText,
        recommended: true,
        role: 'modeling',
        scaffold: '前置情境→任務→觀察項目→事後問題',
        articulation: '受測者做完任務時，你會看哪 3 個訊號？',
        pitfall: '別寫「請告訴我你的感受」——換成觀察行為。',
      },
      {
        id: 'success_metric',
        title: '定義成功/失敗',
        body: '可觀察、可量化',
        icon: Ruler,
        role: 'scaffolding',
        scaffold: '成功＝X% / 時間 / 完成 Y；失敗＝Z',
        articulation: '這個指標能單獨驗證假設嗎？',
        pitfall: '別用「使用者開心」當成功——找可被攝影機抓到的訊號。',
      },
      {
        id: 'fidelity_ceiling',
        title: '保真度上限',
        body: '能回答假設的最小成本',
        icon: Frame,
        role: 'scaffolding',
        scaffold: '紙原型／Wireframe／點擊原型',
        articulation: '再多花一倍時間，能多回答什麼？',
        pitfall: '保真度膨脹 = 學習效率下降。',
      },
      {
        id: 'recruit_users',
        title: '挑受測者',
        body: '對齊 Persona 與 HMW',
        icon: Users,
        role: 'coaching',
        scaffold: '5 人足以發現 80% 可用性問題',
        articulation: '受測者跟你 Persona 的差距在哪？',
        pitfall: '找朋友湊人數 → 訊號偏差。',
      },
    ],
  },

  '4.3': {
    stage: 'deliver',
    narrative: {
      ariaSays:
        '4.3 模擬測試與 Debrief：跑完雛形後逐題填寫三題 Debrief，再決定 Close、Loop to Develop 或 Loop to Define。',
      example: '原本以為使用者要「即時運費」→ 跑完發現「能信任的預估」更重要 → 信念更新。',
      delayJudgment: '別只回顧「結果好不好」——回顧「我們的信念被更新了嗎」。',
    },
    actions: [
      {
        id: 'plan_debrief',
        title: 'Debrief 三題',
        body: '結構化反思',
        icon: TestTube,
        recommended: true,
        role: 'reflection',
        scaffold: '信念更新？／回應 HMW？／下次 Phase 1 怎麼改？',
        articulation: '我們學到什麼能改寫 Phase 1 的事？',
        pitfall: '別變成成果報告——要記錄「假設 vs 觀察」的落差。',
      },
      {
        id: 'belief_diff',
        title: '寫信念更新卡',
        body: '原本 vs 現在',
        icon: Brain,
        role: 'scaffolding',
        scaffold: '「原本以為 X，現在認為 Y，因為 Z」',
        articulation: 'Y 的證據是行為觀察還是受測者口述？',
        pitfall: '只寫「使用者很喜歡」沒用——寫出新洞察。',
      },
      {
        id: 'decide_next',
        title: '決定 Close / Loop',
        body: '三選一不可懸置',
        icon: Compass,
        role: 'articulation',
        scaffold: 'Close ／ Loop to Develop ／ Loop to Define',
        articulation: '你選的這條路，最早會失敗在哪？',
        pitfall: '懸置不決＝下次回來這份原型已過期。',
      },
      {
        id: 'spec_draft',
        title: '草擬 Spec（僅 Close）',
        body: '把假設與 Debrief 串起來',
        icon: LayoutTemplate,
        role: 'coaching',
        scaffold: '決策 ← 假設 ← Debrief ← 訪談 traceback',
        articulation: 'Spec 裡每個決策都能 trace 回某筆訪談嗎？',
        pitfall: 'Loop 路徑不寫 Spec——只 Close 才產出。',
      },
    ],
  },
}
