"""add_micro_phase_support

Revision ID: 1fdee7446bf9
Revises: 9e1810ea2eed
Create Date: 2026-03-30 04:05:30.908524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fdee7446bf9'
down_revision: Union[str, Sequence[str], None] = '9e1810ea2eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_phase_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_micro_phase', sa.String(length=10), nullable=False),
    sa.Column('to_micro_phase', sa.String(length=10), nullable=False),
    sa.Column('transition_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('canvas_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_micro_phase_history_project', 'micro_phase_history', ['project_id'], unique=False)
    op.add_column('agent_decision_trace', sa.Column('micro_phase', sa.String(length=10), nullable=True))
    op.add_column('agent_decision_trace', sa.Column('role_status', sa.String(length=20), nullable=True))
    # Add as nullable first, backfill existing rows, then set NOT NULL
    op.add_column('project', sa.Column('current_micro_phase', sa.String(length=10), nullable=True))
    op.execute("UPDATE project SET current_micro_phase = '1.1' WHERE current_micro_phase IS NULL")
    op.alter_column('project', 'current_micro_phase', nullable=False)
    op.add_column('stage_evaluation_log', sa.Column('micro_phase', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_evaluation_log', 'micro_phase')
    op.drop_column('project', 'current_micro_phase')
    op.drop_column('agent_decision_trace', 'role_status')
    op.drop_column('agent_decision_trace', 'micro_phase')
    op.drop_index('idx_micro_phase_history_project', table_name='micro_phase_history')
    op.drop_table('micro_phase_history')
    # ### end Alembic commands ###
