"""initial_schema

Revision ID: 9e1810ea2eed
Revises: 
Create Date: 2026-03-26 18:11:47.800463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e1810ea2eed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('can_create_project', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_created_by', 'user', ['created_by'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(length=20), nullable=False),
    sa.Column('ai_contribution', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_creator', 'project', ['creator_id'], unique=False)
    op.create_index('idx_project_status', 'project', ['status'], unique=False)
    op.create_table('agent_decision_trace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('assess_result', sa.String(length=20), nullable=False),
    sa.Column('assess_rule', sa.String(length=100), nullable=True),
    sa.Column('assess_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_in', sa.Integer(), nullable=True),
    sa.Column('llm_tokens_out', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_result', sa.String(length=20), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trace_agent', 'agent_decision_trace', ['agent_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_trace_project', 'agent_decision_trace', ['project_id'], unique=False)
    op.create_index('idx_trace_project_time', 'agent_decision_trace', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_project', 'message', ['project_id'], unique=False)
    op.create_index('idx_message_project_time', 'message', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('seat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('seat_role', sa.String(length=20), nullable=False),
    sa.Column('occupant_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'seat_role')
    )
    op.create_index('idx_seat_project', 'seat', ['project_id'], unique=False)
    op.create_table('stage_evaluation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('quantitative_score', sa.Float(), nullable=True),
    sa.Column('qualitative_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('consecutive_pass_count', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_project', 'stage_evaluation_log', ['project_id'], unique=False)
    op.create_table('stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=False),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('canvas_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stage_history_project', 'stage_history', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stage_history_project', table_name='stage_history')
    op.drop_table('stage_history')
    op.drop_index('idx_eval_project', table_name='stage_evaluation_log')
    op.drop_table('stage_evaluation_log')
    op.drop_index('idx_seat_project', table_name='seat')
    op.drop_table('seat')
    op.drop_index('idx_message_project_time', table_name='message')
    op.drop_index('idx_message_project', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_trace_project_time', table_name='agent_decision_trace')
    op.drop_index('idx_trace_project', table_name='agent_decision_trace')
    op.drop_index('idx_trace_agent', table_name='agent_decision_trace')
    op.drop_table('agent_decision_trace')
    op.drop_index('idx_project_status', table_name='project')
    op.drop_index('idx_project_creator', table_name='project')
    op.drop_table('project')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_user_created_by', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
